---  
- hosts: localhost 
  name: Install mongo onto db server
  connection: local
  become: yes
  tasks:
  - name: import variables 
    include_vars: vars/main.yml  
  roles:
  - mrcrilly.mongodb

- hosts: localhost 
  name: Restore Test Database
  connection: local
  tasks:
  - name: Import into the DB
    command: mongorestore files/notinphilly
    tags: "db_restore"
  - name: Remove backup
    file: path=~/notinphilly state=absent
